### PR TITLE
world namespace & some fixes

### LINKED ISSUE #4: Genetic Programming World module
A world should contain all the information needed to run the algorithm.
- Fitness function
- Selection function
- Problem's inputs
- Problem's language
- Mutation, crossover and selection probabilities

...

### PR DESCRIPTION
**Pull request by FelipeRosa**
Basic world functionality, fixed tournament selection implementation (wasn't taking random samples) and gsgp.core now has a working sample of using the library to approximate f(x) = x^2 + 1. This closes #4.

### CODE REVIEW

File: src/gsgp/selection.clj [hunk 1]
```diff
@@ -3,6 +3,6 @@
 
 (defn tournament-selection
   [population tournament-size pressure-coefficient]
-  (let [participants (take tournament-size population)
```
Comment (FelipeRosa) [inline src/gsgp/selection.clj:6]: participants should be a random sample from the population.
